export const data = [
  { id: 1, name: "Activity A", status: "Draft" },
  { id: 2, name: "Activity B", status: "Draft" },
  { id: 3, name: "Activity C", status: "Draft" },
  { id: 4, name: "Activity D", status: "Draft" },
  { id: 5, name: "Activity E", status: "Draft" },
  { id: 6, name: "Activity F", status: "Draft" },
  { id: 7, name: "Activity G", status: "Draft" },
  { id: 8, name: "Activity H", status: "Draft" },
  { id: 9, name: "Activity I", status: "Final" },
  { id: 10, name: "Activity J", status: "Delete" },
  { id: 11, name: "Activity K", status: "Draft" },
  { id: 12, name: "Activity L", status: "Draft" },
  { id: 13, name: "Activity M", status: "Delete" },
  { id: 14, name: "Activity N", status: "Final" },
  { id: 15, name: "Activity O", status: "Final" },
]
